start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_76.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_100.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_124.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_152.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_233.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_246.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_268.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_360.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_380.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_428.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_440.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_528.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_604.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_616.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_620.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_643.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_688.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_703.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_724.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M2" mplus Two-saturated_840.inp
