start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_76.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_100.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_124.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_152.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_233.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_246.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_268.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_360.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_380.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_428.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_440.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_528.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_604.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_616.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_620.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_643.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_688.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_703.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_724.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M9" mplus Final_840.inp
