start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_76.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_100.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_124.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_152.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_233.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_246.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_268.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_360.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_428.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_440.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_528.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_604.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_616.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_620.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_643.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_688.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_703.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_724.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\mod(all)" mplus Mod-all_840.inp
