start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_76.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_100.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_124.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_152.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_233.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_246.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_268.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_360.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_380.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_428.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_440.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_528.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_604.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_616.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_620.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_643.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_688.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_703.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_724.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M3" mplus Two-structured_840.inp
