start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_76.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_100.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_124.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_152.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_233.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_246.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_268.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_360.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_380.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_428.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_440.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_528.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_604.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_616.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_620.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_643.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_688.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_703.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_724.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M1" mplus One-level_840.inp
