start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_76.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_100.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_124.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_152.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_233.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_246.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_268.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_360.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_428.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_440.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_528.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_604.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_616.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_620.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_643.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_688.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_703.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_724.inp
start "" /d "M:\pc\Dokumenter\MSc\Thesis\Mplus\M0" mplus Null_840.inp
